"use strict";

/**
 * Country dataset for Flag Guesser.
 *
 * Each row: [ISO 3166-1 alpha-2 code, name, capital, region, tier]
 * Tier 1 = widely recognised flags, tier 2 = moderately known, tier 3 = hard.
 * Flag images are served from flagcdn.com using the lowercase code.
 */
const COUNTRY_ROWS = [
  // Africa
  ["DZ", "Algeria", "Algiers", "Africa", 2],
  ["AO", "Angola", "Luanda", "Africa", 3],
  ["BJ", "Benin", "Porto-Novo", "Africa", 3],
  ["BW", "Botswana", "Gaborone", "Africa", 3],
  ["BF", "Burkina Faso", "Ouagadougou", "Africa", 3],
  ["BI", "Burundi", "Gitega", "Africa", 3],
  ["CV", "Cabo Verde", "Praia", "Africa", 3],
  ["CM", "Cameroon", "Yaounde", "Africa", 2],
  ["CF", "Central African Republic", "Bangui", "Africa", 3],
  ["TD", "Chad", "N'Djamena", "Africa", 3],
  ["KM", "Comoros", "Moroni", "Africa", 3],
  ["CG", "Republic of the Congo", "Brazzaville", "Africa", 3],
  ["CD", "DR Congo", "Kinshasa", "Africa", 3],
  ["DJ", "Djibouti", "Djibouti", "Africa", 3],
  ["EG", "Egypt", "Cairo", "Africa", 1],
  ["GQ", "Equatorial Guinea", "Malabo", "Africa", 3],
  ["ER", "Eritrea", "Asmara", "Africa", 3],
  ["SZ", "Eswatini", "Mbabane", "Africa", 3],
  ["ET", "Ethiopia", "Addis Ababa", "Africa", 2],
  ["GA", "Gabon", "Libreville", "Africa", 3],
  ["GM", "Gambia", "Banjul", "Africa", 3],
  ["GH", "Ghana", "Accra", "Africa", 2],
  ["GN", "Guinea", "Conakry", "Africa", 3],
  ["GW", "Guinea-Bissau", "Bissau", "Africa", 3],
  ["CI", "Ivory Coast", "Yamoussoukro", "Africa", 2],
  ["KE", "Kenya", "Nairobi", "Africa", 2],
  ["LS", "Lesotho", "Maseru", "Africa", 3],
  ["LR", "Liberia", "Monrovia", "Africa", 3],
  ["LY", "Libya", "Tripoli", "Africa", 3],
  ["MG", "Madagascar", "Antananarivo", "Africa", 3],
  ["MW", "Malawi", "Lilongwe", "Africa", 3],
  ["ML", "Mali", "Bamako", "Africa", 3],
  ["MR", "Mauritania", "Nouakchott", "Africa", 3],
  ["MU", "Mauritius", "Port Louis", "Africa", 3],
  ["MA", "Morocco", "Rabat", "Africa", 2],
  ["MZ", "Mozambique", "Maputo", "Africa", 3],
  ["NA", "Namibia", "Windhoek", "Africa", 3],
  ["NE", "Niger", "Niamey", "Africa", 3],
  ["NG", "Nigeria", "Abuja", "Africa", 2],
  ["RW", "Rwanda", "Kigali", "Africa", 3],
  ["ST", "Sao Tome and Principe", "Sao Tome", "Africa", 3],
  ["SN", "Senegal", "Dakar", "Africa", 3],
  ["SC", "Seychelles", "Victoria", "Africa", 3],
  ["SL", "Sierra Leone", "Freetown", "Africa", 3],
  ["SO", "Somalia", "Mogadishu", "Africa", 3],
  ["ZA", "South Africa", "Pretoria", "Africa", 1],
  ["SS", "South Sudan", "Juba", "Africa", 3],
  ["SD", "Sudan", "Khartoum", "Africa", 3],
  ["TZ", "Tanzania", "Dodoma", "Africa", 3],
  ["TG", "Togo", "Lome", "Africa", 3],
  ["TN", "Tunisia", "Tunis", "Africa", 2],
  ["UG", "Uganda", "Kampala", "Africa", 3],
  ["ZM", "Zambia", "Lusaka", "Africa", 3],
  ["ZW", "Zimbabwe", "Harare", "Africa", 3],

  // Americas
  ["AG", "Antigua and Barbuda", "Saint John's", "Americas", 3],
  ["AR", "Argentina", "Buenos Aires", "Americas", 1],
  ["BS", "Bahamas", "Nassau", "Americas", 3],
  ["BB", "Barbados", "Bridgetown", "Americas", 3],
  ["BZ", "Belize", "Belmopan", "Americas", 3],
  ["BO", "Bolivia", "Sucre", "Americas", 3],
  ["BR", "Brazil", "Brasilia", "Americas", 1],
  ["CA", "Canada", "Ottawa", "Americas", 1],
  ["CL", "Chile", "Santiago", "Americas", 2],
  ["CO", "Colombia", "Bogota", "Americas", 2],
  ["CR", "Costa Rica", "San Jose", "Americas", 3],
  ["CU", "Cuba", "Havana", "Americas", 2],
  ["DM", "Dominica", "Roseau", "Americas", 3],
  ["DO", "Dominican Republic", "Santo Domingo", "Americas", 3],
  ["EC", "Ecuador", "Quito", "Americas", 3],
  ["SV", "El Salvador", "San Salvador", "Americas", 3],
  ["GD", "Grenada", "Saint George's", "Americas", 3],
  ["GT", "Guatemala", "Guatemala City", "Americas", 3],
  ["GY", "Guyana", "Georgetown", "Americas", 3],
  ["HT", "Haiti", "Port-au-Prince", "Americas", 3],
  ["HN", "Honduras", "Tegucigalpa", "Americas", 3],
  ["JM", "Jamaica", "Kingston", "Americas", 2],
  ["MX", "Mexico", "Mexico City", "Americas", 1],
  ["NI", "Nicaragua", "Managua", "Americas", 3],
  ["PA", "Panama", "Panama City", "Americas", 3],
  ["PY", "Paraguay", "Asuncion", "Americas", 3],
  ["PE", "Peru", "Lima", "Americas", 2],
  ["KN", "Saint Kitts and Nevis", "Basseterre", "Americas", 3],
  ["LC", "Saint Lucia", "Castries", "Americas", 3],
  ["VC", "Saint Vincent and the Grenadines", "Kingstown", "Americas", 3],
  ["SR", "Suriname", "Paramaribo", "Americas", 3],
  ["TT", "Trinidad and Tobago", "Port of Spain", "Americas", 3],
  ["US", "United States", "Washington, D.C.", "Americas", 1],
  ["UY", "Uruguay", "Montevideo", "Americas", 3],
  ["VE", "Venezuela", "Caracas", "Americas", 2],

  // Asia
  ["AF", "Afghanistan", "Kabul", "Asia", 3],
  ["AM", "Armenia", "Yerevan", "Asia", 3],
  ["AZ", "Azerbaijan", "Baku", "Asia", 3],
  ["BH", "Bahrain", "Manama", "Asia", 3],
  ["BD", "Bangladesh", "Dhaka", "Asia", 2],
  ["BT", "Bhutan", "Thimphu", "Asia", 3],
  ["BN", "Brunei", "Bandar Seri Begawan", "Asia", 3],
  ["KH", "Cambodia", "Phnom Penh", "Asia", 3],
  ["CN", "China", "Beijing", "Asia", 1],
  ["GE", "Georgia", "Tbilisi", "Asia", 3],
  ["IN", "India", "New Delhi", "Asia", 1],
  ["ID", "Indonesia", "Jakarta", "Asia", 2],
  ["IR", "Iran", "Tehran", "Asia", 2],
  ["IQ", "Iraq", "Baghdad", "Asia", 2],
  ["IL", "Israel", "Jerusalem", "Asia", 2],
  ["JP", "Japan", "Tokyo", "Asia", 1],
  ["JO", "Jordan", "Amman", "Asia", 3],
  ["KZ", "Kazakhstan", "Astana", "Asia", 3],
  ["KW", "Kuwait", "Kuwait City", "Asia", 3],
  ["KG", "Kyrgyzstan", "Bishkek", "Asia", 3],
  ["LA", "Laos", "Vientiane", "Asia", 3],
  ["LB", "Lebanon", "Beirut", "Asia", 2],
  ["MY", "Malaysia", "Kuala Lumpur", "Asia", 2],
  ["MV", "Maldives", "Male", "Asia", 3],
  ["MN", "Mongolia", "Ulaanbaatar", "Asia", 3],
  ["MM", "Myanmar", "Naypyidaw", "Asia", 3],
  ["NP", "Nepal", "Kathmandu", "Asia", 2],
  ["KP", "North Korea", "Pyongyang", "Asia", 3],
  ["OM", "Oman", "Muscat", "Asia", 3],
  ["PK", "Pakistan", "Islamabad", "Asia", 1],
  ["PS", "Palestine", "Ramallah", "Asia", 2],
  ["PH", "Philippines", "Manila", "Asia", 2],
  ["QA", "Qatar", "Doha", "Asia", 2],
  ["SA", "Saudi Arabia", "Riyadh", "Asia", 1],
  ["SG", "Singapore", "Singapore", "Asia", 2],
  ["KR", "South Korea", "Seoul", "Asia", 1],
  ["LK", "Sri Lanka", "Sri Jayawardenepura Kotte", "Asia", 2],
  ["SY", "Syria", "Damascus", "Asia", 3],
  ["TW", "Taiwan", "Taipei", "Asia", 2],
  ["TJ", "Tajikistan", "Dushanbe", "Asia", 3],
  ["TH", "Thailand", "Bangkok", "Asia", 2],
  ["TL", "Timor-Leste", "Dili", "Asia", 3],
  ["TR", "Turkey", "Ankara", "Asia", 1],
  ["TM", "Turkmenistan", "Ashgabat", "Asia", 3],
  ["AE", "United Arab Emirates", "Abu Dhabi", "Asia", 1],
  ["UZ", "Uzbekistan", "Tashkent", "Asia", 3],
  ["VN", "Vietnam", "Hanoi", "Asia", 2],
  ["YE", "Yemen", "Sana'a", "Asia", 3],

  // Europe
  ["AL", "Albania", "Tirana", "Europe", 3],
  ["AD", "Andorra", "Andorra la Vella", "Europe", 3],
  ["AT", "Austria", "Vienna", "Europe", 2],
  ["BY", "Belarus", "Minsk", "Europe", 3],
  ["BE", "Belgium", "Brussels", "Europe", 2],
  ["BA", "Bosnia and Herzegovina", "Sarajevo", "Europe", 3],
  ["BG", "Bulgaria", "Sofia", "Europe", 3],
  ["HR", "Croatia", "Zagreb", "Europe", 3],
  ["CY", "Cyprus", "Nicosia", "Europe", 3],
  ["CZ", "Czechia", "Prague", "Europe", 3],
  ["DK", "Denmark", "Copenhagen", "Europe", 2],
  ["EE", "Estonia", "Tallinn", "Europe", 3],
  ["FI", "Finland", "Helsinki", "Europe", 2],
  ["FR", "France", "Paris", "Europe", 1],
  ["DE", "Germany", "Berlin", "Europe", 1],
  ["GR", "Greece", "Athens", "Europe", 2],
  ["HU", "Hungary", "Budapest", "Europe", 3],
  ["IS", "Iceland", "Reykjavik", "Europe", 3],
  ["IE", "Ireland", "Dublin", "Europe", 2],
  ["IT", "Italy", "Rome", "Europe", 1],
  ["XK", "Kosovo", "Pristina", "Europe", 3],
  ["LV", "Latvia", "Riga", "Europe", 3],
  ["LI", "Liechtenstein", "Vaduz", "Europe", 3],
  ["LT", "Lithuania", "Vilnius", "Europe", 3],
  ["LU", "Luxembourg", "Luxembourg", "Europe", 3],
  ["MT", "Malta", "Valletta", "Europe", 3],
  ["MD", "Moldova", "Chisinau", "Europe", 3],
  ["MC", "Monaco", "Monaco", "Europe", 3],
  ["ME", "Montenegro", "Podgorica", "Europe", 3],
  ["NL", "Netherlands", "Amsterdam", "Europe", 2],
  ["MK", "North Macedonia", "Skopje", "Europe", 3],
  ["NO", "Norway", "Oslo", "Europe", 2],
  ["PL", "Poland", "Warsaw", "Europe", 2],
  ["PT", "Portugal", "Lisbon", "Europe", 2],
  ["RO", "Romania", "Bucharest", "Europe", 3],
  ["RU", "Russia", "Moscow", "Europe", 1],
  ["SM", "San Marino", "San Marino", "Europe", 3],
  ["RS", "Serbia", "Belgrade", "Europe", 3],
  ["SK", "Slovakia", "Bratislava", "Europe", 3],
  ["SI", "Slovenia", "Ljubljana", "Europe", 3],
  ["ES", "Spain", "Madrid", "Europe", 1],
  ["SE", "Sweden", "Stockholm", "Europe", 2],
  ["CH", "Switzerland", "Bern", "Europe", 1],
  ["UA", "Ukraine", "Kyiv", "Europe", 2],
  ["GB", "United Kingdom", "London", "Europe", 1],
  ["VA", "Vatican City", "Vatican City", "Europe", 3],

  // Oceania
  ["AU", "Australia", "Canberra", "Oceania", 1],
  ["FJ", "Fiji", "Suva", "Oceania", 3],
  ["KI", "Kiribati", "Tarawa", "Oceania", 3],
  ["MH", "Marshall Islands", "Majuro", "Oceania", 3],
  ["FM", "Micronesia", "Palikir", "Oceania", 3],
  ["NR", "Nauru", "Yaren", "Oceania", 3],
  ["NZ", "New Zealand", "Wellington", "Oceania", 2],
  ["PW", "Palau", "Ngerulmud", "Oceania", 3],
  ["PG", "Papua New Guinea", "Port Moresby", "Oceania", 3],
  ["WS", "Samoa", "Apia", "Oceania", 3],
  ["SB", "Solomon Islands", "Honiara", "Oceania", 3],
  ["TO", "Tonga", "Nuku'alofa", "Oceania", 3],
  ["TV", "Tuvalu", "Funafuti", "Oceania", 3],
  ["VU", "Vanuatu", "Port Vila", "Oceania", 3]
];

/** @typedef {{ code: string, name: string, capital: string, region: string, tier: number }} Country */

/** @type {ReadonlyArray<Country>} */
const COUNTRIES = Object.freeze(
  COUNTRY_ROWS.map(([code, name, capital, region, tier]) =>
    Object.freeze({ code, name, capital, region, tier })
  )
);

/** Region filters offered on the setup screen. */
const REGIONS = Object.freeze([
  { id: "world", label: "Whole world" },
  { id: "Africa", label: "Africa" },
  { id: "Americas", label: "Americas" },
  { id: "Asia", label: "Asia" },
  { id: "Europe", label: "Europe" },
  { id: "Oceania", label: "Oceania" }
]);

/**
 * Groups of flags that are easy to mix up. When a question targets a flag
 * in a group, the engine prefers other members of that group as distractors.
 */
const CONFUSABLE_GROUPS = Object.freeze([
  ["RO", "TD", "AD", "MD"],
  ["ID", "MC", "PL", "SG"],
  ["AU", "NZ", "FJ", "TV"],
  ["NO", "IS", "DK", "SE", "FI"],
  ["NL", "LU", "RU", "SI", "SK", "RS", "HR"],
  ["IE", "CI", "IT", "MX"],
  ["CO", "EC", "VE"],
  ["SV", "NI", "HN", "AR", "GT"],
  ["SN", "ML", "GN", "CM", "GH", "BO"],
  ["QA", "BH"],
  ["AE", "KW", "JO", "PS", "SD", "IQ", "SY", "YE", "EG"],
  ["LI", "HT"],
  ["TR", "TN"],
  ["MY", "US", "LR"],
  ["IN", "NE"],
  ["GR", "UY"],
  ["CL", "CU"],
  ["BE", "DE"],
  ["AT", "LV"],
  ["BG", "HU"],
  ["AZ", "UZ", "TM"],
  ["LT", "GH", "BO"],
  ["JP", "BD", "PW"],
  ["FR", "NL", "LU"],
  ["GB", "AU", "NZ"],
  ["CN", "VN"],
  ["PE", "CA"],
  ["MN", "KG"],
  ["SO", "FM"],
  ["TH", "CR"],
  ["MW", "ZM", "ZW", "MZ"],
  ["PY", "NL"],
  ["ES", "PT"],
  ["SA", "PK"],
  ["KR", "TW"],
  ["CH", "VA"],
  ["EE", "GA"],
  ["GY", "SC"],
  ["BA", "XK"],
  ["ME", "BY"],
  ["KZ", "PS", "AE"]
]);

if (typeof module === "object" && module.exports) {
  module.exports = { COUNTRIES, REGIONS, CONFUSABLE_GROUPS };
}
